### ISSUE TITLE
Threadcap: Add support for the "summary" property

### ISSUE THREAD

**Issue by dellagustin** [skymethod/minipub#6]
Hello @johnspurlock-skymethod ,

While testing I noticed that threadcap is not supporting the `summary` property.
According to my tests, this property is used to store _Content Warnings_ (e.g. spoiler alert, sensitive content). See references below.

It would be nice to have this property supported in threadcap.

![image](https://user-images.githubusercontent.com/260113/215614200-6a8d9a75-10a8-4425-a157-1a808201ee69.png)

![image](https://user-images.githubusercontent.com/260113/215613647-7f3702e8-1dcd-4de6-b14b-685f483c526a.png)

https://fosstodon.org/@dellagustin/109780550965092145

```js
{
    "@context": [
        "https://www.w3.org/ns/activitystreams",
        {
            "ostatus": "http://ostatus.org#",
            "atomUri": "ostatus:atomUri",
            "inReplyToAtomUri": "ostatus:inReplyToAtomUri",
            "conversation": "ostatus:conversation",
            "sensitive": "as:sensitive",
            "toot": "http://joinmastodon.org/ns#",
            "votersCount": "toot:votersCount"
        }
    ],
    "id": "https://fosstodon.org/users/dellagustin/statuses/109780550965092145",
    "type": "Note",
    "summary": "Testing content warning",
    "inReplyTo": null,
    "published": "2023-01-30T22:37:50Z",
    "url": "https://fosstodon.org/@dellagustin/109780550965092145",
    "attributedTo": "https://fosstodon.org/users/dellagustin",
    "to": [
        "https://www.w3.org/ns/activitystreams#Public"
    ],
    "cc": [
        "https://fosstodon.org/users/dellagustin/followers"
    ],
    "sensitive": true,
    "atomUri": "https://fosstodon.org/users/dellagustin/statuses/109780550965092145",
    "inReplyToAtomUri": null,
    "conversation": "tag:fosstodon.org,2023-01-30:objectId=84208846:objectType=Conversation",
    "content": "<p>A message with content warning.</p>",
    "contentMap": {
        "en": "<p>A message with content warning.</p>"
    },
    "attachment": [],
    "tag": [],
    "replies": {
        "id": "https://fosstodon.org/users/dellagustin/statuses/109780550965092145/replies",
        "type": "Collection",
        "first": {
            "type": "CollectionPage",
            "next": "https://fosstodon.org/users/dellagustin/statuses/109780550965092145/replies?only_other_accounts=true&page=true",
            "partOf": "https://fosstodon.org/users/dellagustin/statuses/109780550965092145/replies",
            "items": []
        }
    }
}
```

**Comment by johnspurlock-skymethod** [comment]
Remember threadcap started as a way to normalize comments coming from AP or twitter (and an old thing based on fountain comments).  But now that AP is a bit more in focus, I agree that summary, at least, would be a nice addition to the payload.

**Comment by johnspurlock-skymethod** [comment]
Added in 0.1.10

https://www.npmjs.com/package/threadcap/v/0.1.10

**Comment by dellagustin** [comment]
That is great! Thanks a lot.

> Remember threadcap started as a way to normalize comments coming from AP or twitter (and an old thing based on fountain comments). But now that AP is a bit more in focus, I agree that summary, at least, would be a nice addition to the payload.

Even if twitter was still in the game, I think it would still make sense to add summary. It is a backwards compatible addition for a feature that would simply not be present for twitter (shame on them 😃).
